---
- name: Setup repos
  lineinfile:
    path: /etc/apt/sources.list
    line: "{{item}}"
  with_items:
    - deb https://apt.dockerproject.org/repo debian-stretch main
    - deb https://packages.microsoft.com/repos/vscode stable main

- name: Setup alias's
  lineinfile:
    path: /root/.bash_aliases
    line: "{{item}}"
  with_items:
    - alias http='python -m SimpleHTTPServer 8000'


- name: Add i386
  shell: dpkg --add-architecture i386

- name: Get docker repo keys
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: get microsoft keys
  shell: |
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Update apt Cache
  apt:
    update_cache: yes

- name: Install stuff <<-- Takes a while
  apt: name={{ item }} state=present install_recommends=yes force_apt_get=yes
  with_items:
    - spice-vdagent
    - ansible
    - libncurses5-dev
    - docker-engine
    - "libc6:i386"
    - code
    - g++
    - libssl-dev
    - audacity
    - bkhive
    - wine32
    - libgmp3-dev
    - libgmp-dev
    - libz-dev
    - unar
    - cmake
    - asciinema
    - crackle
    - kali-linux-pwtools
    - python-aff4
    - python-oletools
    - rsakeyfind
    - creddump7
    - gimp
    - python-pyotp

  #not sure why this dont want to install normally
- name: Install python-dev
  warn: False
  shell: apt-get install python-dev -y


- name: Install pip's
  pip:
    name: "{{item}}"
  with_items:
   - pwntools
   - requests
   - pandas
   - capstone
   - pdfkit
   - Pillow

- name: Creates ctf dir
  file: path=/root/ctf state=directory