---
- name: Check for tattoo
  win_stat:
    path: c:\tattoo
  register: fc


- name: Set services to stopped
  when: false
  win_service:
    name: "{{ item }}"
    start_mode: disabled
    state: stopped
  with_items:
    - WinDefend


- name: enable unsigned drivers
  when: fc.stat.exists == False
  win_shell: bcdedit.exe /set nointegritychecks ON 
- win_reboot:
    reboot_timeout: 3600
  when: fc.stat.exists == False

- name: Make tattoo
  win_file:
    path: C:\tattoo
    state: touch

- name: Disable windefender
  win_shell: "Set-MpPreference -DisableRealtimeMonitoring $true"

- name: Install spice-quest-tools
  win_package:
    path: https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe
    product_id: "{8122E54F-475E-4DA7-BEC2-B6B2DE16A988}"
    arguments: /S

- name: Check for firefox before install
  win_stat:
    path: C:\Program Files\Mozilla Firefox\firefox.exe
  register: fc

- name: Install firefox
  when: fc.stat.exists == False
  win_package:
    path: https://ftp.mozilla.org/pub/firefox/releases/61.0b5/win64/en-US/Firefox%20Setup%2061.0b5.exe
    product_id: creates_*
    arguments: -ms

- name: Install python2.7
  win_package:
    path: https://www.python.org/ftp/python/2.7.15/python-2.7.15.amd64.msi
    product_id: "{16CD92A4-0152-4CB7-8FD6-9788D3363617}"
    arguments: /q

- name: Check for fiddler before install
  win_stat:
    path: C:\Users\ctf\AppData\Local\Programs\Fiddler\Fiddler.exe
  register: fc

- name: Install fiddler
  when: fc.stat.exists == False
  win_package:
    path: https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe
    product_id: creates_*
    arguments: /S

- name: Check for 7zip before install
  win_stat:
    path: C:\Program Files\7-Zip\7z.exe
  register: fc

- name: Install 7zip
  when: fc.stat.exists == False
  win_package:
    path: https://www.7-zip.org/a/7z1805-x64.exe
    product_id: creates_*
    arguments: /S

- name: Check for Systernals Suite before install
  win_stat:
    path: C:\Users\ctf\Desktop\systernals
  register: fc


- name: Get Systernals Suite
  when: fc.stat.exists == False
  win_get_url:
    url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: C:\Windows\Temp\systen.zip

- name: Unpack Systernals Suite
  win_unzip:
    src: C:\Windows\Temp\systen.zip
    dest: C:\Users\ctf\Desktop\systernals
    creates: C:\Users\ctf\Desktop\systernals

- name: Check for Autopsy before install
  win_stat:
    path: C:\Program Files\Autopsy-4.7.0\icon.ico
  register: fc


- name: Get Autopsy
  when: fc.stat.exists == False
  win_get_url:
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
    url: https://github.com/sleuthkit/autopsy/releases/download/autopsy-4.7.0/autopsy-4.7.0-64bit.msi
    dest: C:\Windows\Temp\autopsy.msi

- name: Install Autopsy
  when: fc.stat.exists == False
  win_package:
    path: C:\Windows\Temp\autopsy.msi
    product_id: creates_*
    arguments: /q

- name: Check for Autopsy before install
  win_stat:
    path: C:\Program Files\IDA Freeware 7.0
  register: fc

- name: Install IDA Free Version
  when: fc.stat.exists == False
  win_package:
    path: https://out7.hex-rays.com/files/idafree70_windows.exe
    product_id: creates_*
    arguments: /verysilent
